"""empty message

Revision ID: 2184f49562aa
Revises:
Create Date: 2023-01-17 16:38:24.673151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2184f49562aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('todos', schema=None) as batch_op_1:
        batch_op_1.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    # with op.batch_alter_table('todos', schema=None) as batch_op_2:
    #     batch_op_2.alter_column('todos', 'completed', nullable=False)
    op.alter_column('todos', 'completed', nullable = False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
