"""empty message

Revision ID: 01ef3dc345e0
Revises: b72c26b09747
Create Date: 2023-01-10 16:04:21.386322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ef3dc345e0'
down_revision = 'b72c26b09747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('todos', schema=None) as batch_op_1:
        batch_op_1.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    # with op.batch_alter_table('todos', schema=None) as batch_op_2:
    #     batch_op_2.alter_column('todos', 'completed', nullable=False)
    op.alter_column('todos', 'completed', nullable = False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
